### ISSUE TITLE
No "simulation" directory

### ISSUE THREAD

**Issue by jakeykj** [ruoqi-liu/DSW#1]
Hi! Thanks for making the codes available. I would like to try out the model on MIMIC-III dataset, but seems the directory "simulation" containing the pre-processing codes (cd simulation; python pre_mimic.py) is not in the repo. Would it be possible to also publish this directory?

Thanks for your help!

**Comment by ruoqi-liu** [comment]
Hi, Thanks for following our work. 
This paper is going to be published in ICDM 2020. We will release a more complete version of the codes including data preprocessing after the conference (by Nov. 20).

**Comment by jakeykj** [comment]
I see, I will check them out later then. Thanks a lot for your reply!
